#! /bin/bash
# vim: filetype=sh

# Copyright (C) 2016-2018 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e -u -o pipefail
set -x

# For coq 8.4
sudo tee /etc/apt/sources.list.d/jessie.list <<'EOF'
deb http://deb.debian.org/debian jessie main
deb-src http://deb.debian.org/debian jessie main
EOF

sudo tee /etc/apt/sources.list.d/backports.list <<'EOF'
deb http://ftp.debian.org/debian stretch-backports main
deb-src http://ftp.debian.org/debian stretch-backports main
EOF

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install -y --no-install-recommends \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common

sudo apt-get update -y

sudo apt-get install -y --no-install-recommends \
  jq \
  lmodern \
  make \
  texlive

sudo apt-get install -y --no-install-recommends \
  -t stretch-backports \
  git

sudo apt-get install -y --no-install-recommends \
  coq-theories=8.4pl4dfsg-1 \
  coq=8.4pl4dfsg-1 \
  libcoq-ocaml=8.4pl4dfsg-1 \
  liblablgtk2-ocaml=2.16.0+dfsg-1 \
  ocaml-base-nox=4.01.0-5

sudo apt-get clean
sudo apt-get autoclean

curl -sL -o /tmp/bats-v0.4.0.tar.gz \
  'https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz'

sha256sum -c - <<'EOF'
480d8d64f1681eee78d1002527f3f06e1ac01e173b761bc73d0cf33f4dc1d8d7  /tmp/bats-v0.4.0.tar.gz
EOF

sudo tar -C /opt -xzf /tmp/bats-v0.4.0.tar.gz

rm /tmp/bats-v0.4.0.tar.gz

sudo tee /etc/profile.d/way.sh <<'EOF'
export PATH="$PATH:/sbin"
export PATH="$PATH:/way/src/infrastructure/bin"
export PATH="$PATH:/opt/bats-0.4.0/bin"
EOF
