#! /bin/bash
# vim: set fenc=utf-8 ff=unix sts=2 sw=2 et ft=sh :

# Copyright (C) 2016-2018 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e -u -o pipefail
set -x

apt-get update -y
apt-get upgrade -y
apt-get install -y --no-install-recommends sudo

useradd way -m -G sudo
USER=way

cat >> /etc/sudoers.d/way <<'EOF'
way ALL=(ALL) NOPASSWD:ALL
EOF

touch ~way/.sudo_as_admin_successful

. '/common'
