#! /bin/bash
# vim: filetype=sh

# Copyright (C) 2016-2018 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e -u -o pipefail
set -x

. '/vagrant/infrastructure/provisioning/common'

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88 | fgrep -q 'Docker Release (CE deb)'
sudo add-apt-repository \
 "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt-get update -y

sudo apt-get install -y --no-install-recommends \
  bash-completion \
  build-essential \
  docker-ce \
  dstat \
  iftop \
  iotop \
  iperf \
  lsof \
  man-db \
  mlocate \
  nano \
  rlwrap \
  strace \
  sysstat \
  tmux \
  unzip \
  vim-nox-py2 \
  wget \
  zip

sudo usermod -aG docker "$USER"

# Color prompts
sed -i 's|#force_color|force_color|' "$HOME/.bashrc"

# UTC timezone
sudo timedatectl set-timezone UTC

# Softlink to code
sudo ln -sfT /vagrant "$HOME/way"
