# vim: filetype=ruby
# Copyright (C) 2016-2016 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

PROJECT_NAME = '@PROJECT_NAME@'

common = File.expand_path('../vendor/infrastructure/vagrant/common', __FILE__)
load common if File.exists?(common)

Vagrant.configure('2') do |config|
end
