#! /bin/bash

set -e -u -o pipefail
set -x

. "$PROJECT_DIR/provisioning/client-vagrant"
. "$PROJECT_DIR/provisioning/common"

sudo add-apt-repository -y ppa:brightbox/ruby-ng
sudo apt-get update

sudo apt-get install -y \
  ruby2.2
