#! /bin/bash

# Copyright (C) 2016-2016 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

set -e -u -o pipefail
set -x

. "$PROJECT_DIR/vendor/infrastructure/provisioning/client-vagrant"
. "$PROJECT_DIR/provisioning/common"

sudo apt-get install -y \
  apache2

# Expose the coq docs in the default virtual host
sudo ln -sfT /usr/share/doc/coq-theories/html /var/www/html/coq
