#! /bin/bash

# Copyright (C) 2016-2016 Philip H. Smith

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# Scan for files that have no or stale boilerplate, such as copyright notices.

set -e -u -o pipefail

function has_copyright_notice {
  # "C''" prevents false matches from the grep pattern itself
  if ! grep -q 'C''opyright .* 2016-.* Philip H. Smith' "$1"
  then
    >&2 echo "Missing copyright notice in $1"
    return 1
  fi
}

function has_current_end_year {
  if ! grep -q "C""opyright .* 2016-$(date +%Y) Philip H. Smith" "$1"
  then
    >&2 echo "Missing current year in copyright notice in $1"
    return 1
  fi
}

function has_gpl_boilerplate {
  if ! grep -q 'under the terms of the GNU General Public License' "$1"
  then
    >&2 echo "Missing GPL boilerplate in $1"
    return 1
  fi
}

function has_vim_modeline {
  if ! grep -q ' vim: filetype=' "$1"
  then
    >&2 echo "Missing vim modeline in $1"
    return 1
  fi
}

export -f has_copyright_notice
export -f has_current_end_year
export -f has_gpl_boilerplate
export -f has_vim_modeline

! find .  \
  -name '.git*' -prune -o \
  -name .check-boilerplate -prune -o \
  -name .editorconfig -prune -o  \
  -name .travis.yml -prune -o \
  -name .vagrant -prune -o  \
  -name GPL-3 -prune -o \
  -name LICENSE -prune -o \
  -name vendor -prune -o  \
  -name version -prune -o \
  $(test -f .check-boilerplate && cat .check-boilerplate) \
  -type f \
  -exec bash -c 'has_copyright_notice "$0"' '{}' \; \
  -exec bash -c 'has_current_end_year "$0"' '{}' \; \
  -exec bash -c 'has_gpl_boilerplate "$0"' '{}' \;  \
  -exec bash -c 'has_vim_modeline "$0"' '{}' \;     \
  -print 2>&1 >/dev/null  | \
grep .
